project:
  type: book
  output-dir: docs


book:
  title: "Relatório de Gestão da Ouvidoria Nacional dos Serviços Penais"
  author: "Ouvidoria Nacional dos Serviços Penais"
  #date: today
  reader-mode: true
  page-navigation: true
  page-footer:
   background: "#294661"
   center:
    - text: "Secretaria Nacional de Políticas Penais - Senappen"
      href: https://www.gov.br/depen/pt-br
    - text: "Ministério da Justiça e Segurança Pública - MJSP"
      href: https://www.gov.br/mj/pt-br
  cover-image: images/senappen_brasao.png
  #logo: images/brasao_ouvidoria.jpeg
  image: images/senappen_brasao.png
  site-url: https://www.gov.br/depen/pt-br
  sharing: [twitter, facebook, linkedin]
  search:
    location: sidebar
    type: textbox

  sidebar:
    font.family: 'Calibri'
    title: "Ouvidoria Nacional dos Serviços Penais"
    subtitle: "Relatório de Gestão"
    background: "white"
    items:
    logo: images/senappen_brasao.png
    style: docked
    alignment: left
    tools:
      - icon: git
      - href: https://www.gov.br/depen/pt-br/canais_atendimento/ouvidoria

  chapters:
    - index.qmd
    - introducao.qmd
    - projetos.qmd
    - acoes.qmd
    - part: tratamento_demandas.qmd
      chapters:
      - estatisticas_anuais.qmd
      - estatisticas_2020.qmd
      - estatisticas_2021.qmd
      - estatisticas_2022.qmd
    - consideracoes.qmd



bibliography: referencias.bib

format:
  html:
    embed-resources: false #COLOCA TODOS OS ARQUIVOS JUNTOS
    theme: cosmo
    code-link: true
    css: style.css
    #page-layout: custom
  pdf:
    documentclass: scrreprt

knitr:
  opts_chunk:
    fig.align: "center"
    message: false
    echo: false
    results: true
    dpi: 300
    warning: false
    out-width: NULL
    fig.responsive: TRUE


lang: pt
csl: abnt.csl

editor: visual


